name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.21"
      
      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -o books-windows.exe
          GOOS=darwin GOARCH=amd64 go build -o books-darwin
          GOOS=linux GOARCH=amd64 go build -o books-linux

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            books-windows.exe
            books-darwin
            books-linux
